development:
  adapter: postgresql
  database: kitchen_helper_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: kitchen_helper_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: kitchen_helper_production
  pool: 5
  timeout: 5000
